### ISSUE TITLE
Přidání error baru

### ISSUE THREAD

**Issue by mskl** [MSKL/fit-bi-si1#1]
Pod horní panel by se hodilo přidat error výpis - například pro informaci uživatele o neplatném přihlášení, o neplatném parametru při úpravě závodu etc.. Pokud bude parametr errormsg prázdný, lišta se nezobrazí. 
![heslo](https://user-images.githubusercontent.com/9153692/39297769-af864e2c-4944-11e8-8056-5d0292246682.jpg)

**Comment by langrlukas** [comment]
Přidáno v
https://github.com/MSKL/fit-bi-si1/commit/33ed0cc8a08c5c47973a835c9d956e2f2785d46a

**Comment by mskl** [comment]
Přesunout error bar do base a předávát zprávu o chybě přímo z kódu namísto hardoced zprávy v HTML.

**Comment by langrlukas** [comment]
Opraveno
